# Generated by Django 5.0.3 on 2024-03-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_sale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
